# Generated by Django 2.0rc1 on 2017-11-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=5)),
                ('prix', models.DecimalField(decimal_places=4, max_digits=4)),
                ('date_ajout', models.DateTimeField()),
            ],
        ),
    ]
