# Generated by Django 2.0rc1 on 2017-11-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ave_cesar', '0003_auto_20171128_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
